In [6]:
import pandas as pd
import pandasql as pdsql

In [2]:
%%writefile earthquake.csv
magnitude,year_2000,year_2001,year_2002,year_2003,year_2004,year_2005,year_2006,year_2007,year_2008,year_2009,year_2010,year_2011,year_2012,id
8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
6.0 to 6.9,146.0,121.0,127.0,140.0,141.0,140.0,142.0,178.0,168.0,144.0,150.0,185.0,108.0,3
5.0 to 5.9,1344.0,1224.0,1201.0,1203.0,1515.0,1693.0,1712.0,2074.0,1768.0,1896.0,2209.0,2276.0,1401.0,4
4.0 to 4.9,8008.0,7991.0,8541.0,8462.0,10888.0,13917.0,12838.0,12078.0,12291.0,6805.0,10164.0,13315.0,9534.0,5
3.0 to 3.9,4827.0,6266.0,7068.0,7624.0,7932.0,9191.0,9990.0,9889.0,11735.0,2905.0,4341.0,2791.0,2453.0,6
2.0 to 2.9,3765.0,4164.0,6419.0,7727.0,6316.0,4636.0,4027.0,3597.0,3860.0,3014.0,4626.0,3643.0,3111.0,7
1.0 to 1.9,1026.0,944.0,1137.0,2506.0,1344.0,26.0,18.0,42.0,21.0,26.0,39.0,47.0,43.0,8
0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10

Writing earthquake.csv

In [7]:
df = pd.read_csv('earthquake.csv')
df.head()

,magnitude,year_2000,year_2001,year_2002,year_2003,year_2004,year_2005,year_2006,year_2007,year_2008,year_2009,year_2010,year_2011,year_2012,id
0,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
1,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
2,6.0 to 6.9,146.0,121.0,127.0,140.0,141.0,140.0,142.0,178.0,168.0,144.0,150.0,185.0,108.0,3
3,5.0 to 5.9,1344.0,1224.0,1201.0,1203.0,1515.0,1693.0,1712.0,2074.0,1768.0,1896.0,2209.0,2276.0,1401.0,4
4,4.0 to 4.9,8008.0,7991.0,8541.0,8462.0,10888.0,13917.0,12838.0,12078.0,12291.0,6805.0,10164.0,13315.0,9534.0,5

In [32]:
#1). using pd.melt function 
new_df=pd.melt(df, id_vars=['magnitude'],
               value_vars=['year_2000','year_2001','year_2002','year_2003','year_2004','year_2005', 'year_2006','year_2007','year_2008','year_2009','year_2010','year_2011','year_2012'],
               var_name='year', value_name='number_of_earthq')

In [33]:
#clean the Year column
new_df['year']=new_df['year'].str.replace('year_','')

In [34]:
new_df.head()

    magnitude  year  number_of_earthq
0  8.0 to 9.9  2000               1.0
1  7.0 to 7.9  2000              14.0
2  6.0 to 6.9  2000             146.0
3  5.0 to 5.9  2000            1344.0
4  4.0 to 4.9  2000            8008.0

In [8]:
#2)pandas sql 
pysqldf = lambda q: pdsql.sqldf(q, globals())

In [9]:
# run any valid sql query
pysqldf('select * from df limit(5)')

,magnitude,year_2000,year_2001,year_2002,year_2003,year_2004,year_2005,year_2006,year_2007,year_2008,year_2009,year_2010,year_2011,year_2012,id
0,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
1,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
2,6.0 to 6.9,146.0,121.0,127.0,140.0,141.0,140.0,142.0,178.0,168.0,144.0,150.0,185.0,108.0,3
3,5.0 to 5.9,1344.0,1224.0,1201.0,1203.0,1515.0,1693.0,1712.0,2074.0,1768.0,1896.0,2209.0,2276.0,1401.0,4
4,4.0 to 4.9,8008.0,7991.0,8541.0,8462.0,10888.0,13917.0,12838.0,12078.0,12291.0,6805.0,10164.0,13315.0,9534.0,5

In [19]:
# hardcoded values
pysqldf("""
SELECT years.*
    FROM 
    (   SELECT 2000 AS year
        UNION SELECT 2001 UNION SELECT 2002 UNION SELECT 2003
        UNION SELECT 2004 UNION SELECT 2005 UNION SELECT 2006
        UNION SELECT 2007 UNION SELECT 2008 UNION SELECT 2009
        UNION SELECT 2010 UNION SELECT 2011 UNION SELECT 2012
    )   years
""")

    year
0   2000
1   2001
2   2002
3   2003
4   2004
5   2005
6   2006
7   2007
8   2008
9   2009
10  2010
11  2011
12  2012

In [17]:
#concatenate cross product of years and all df rows
pysqldf("""
SELECT
    test.year as year,
    df.*
FROM df
CROSS JOIN
(SELECT years.*
        FROM 
    (   SELECT 2000 AS year
        UNION SELECT 2001 UNION SELECT 2002 UNION SELECT 2003
        UNION SELECT 2004 UNION SELECT 2005 UNION SELECT 2006
        UNION SELECT 2007 UNION SELECT 2008 UNION SELECT 2009
        UNION SELECT 2010 UNION SELECT 2011 UNION SELECT 2012
    ) years
 ) test 
""")

,year,magnitude,year_2000,year_2001,year_2002,year_2003,year_2004,year_2005,year_2006,year_2007,year_2008,year_2009,year_2010,year_2011,year_2012,id
0,2000,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
1,2001,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
2,2002,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
3,2003,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
4,2004,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
5,2005,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
6,2006,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
7,2007,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
8,2008,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
9,2009,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
10,2010,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
11,2011,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
12,2012,8.0 to 9.9,1.0,1.0,0.0,1.0,2.0,1.0,2.0,4.0,0.0,1.0,1.0,1.0,2.0,1
13,2000,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
14,2001,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
15,2002,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
16,2003,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
17,2004,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
18,2005,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
19,2006,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
20,2007,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
21,2008,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
22,2009,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
23,2010,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
24,2011,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
25,2012,7.0 to 7.9,14.0,15.0,13.0,14.0,14.0,10.0,9.0,14.0,12.0,16.0,23.0,19.0,12.0,2
26,2000,6.0 to 6.9,146.0,121.0,127.0,140.0,141.0,140.0,142.0,178.0,168.0,144.0,150.0,185.0,108.0,3
27,2001,6.0 to 6.9,146.0,121.0,127.0,140.0,141.0,140.0,142.0,178.0,168.0,144.0,150.0,185.0,108.0,3
28,2002,6.0 to 6.9,146.0,121.0,127.0,140.0,141.0,140.0,142.0,178.0,168.0,144.0,150.0,185.0,108.0,3
29,2003,6.0 to 6.9,146.0,121.0,127.0,140.0,141.0,140.0,142.0,178.0,168.0,144.0,150.0,185.0,108.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2009,1.0 to 1.9,1026.0,944.0,1137.0,2506.0,1344.0,26.0,18.0,42.0,21.0,26.0,39.0,47.0,43.0,8
101,2010,1.0 to 1.9,1026.0,944.0,1137.0,2506.0,1344.0,26.0,18.0,42.0,21.0,26.0,39.0,47.0,43.0,8
102,2011,1.0 to 1.9,1026.0,944.0,1137.0,2506.0,1344.0,26.0,18.0,42.0,21.0,26.0,39.0,47.0,43.0,8
103,2012,1.0 to 1.9,1026.0,944.0,1137.0,2506.0,1344.0,26.0,18.0,42.0,21.0,26.0,39.0,47.0,43.0,8
104,2000,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
105,2001,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
106,2002,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
107,2003,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
108,2004,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
109,2005,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
110,2006,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
111,2007,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
112,2008,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
113,2009,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
114,2010,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
115,2011,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
116,2012,0.1 to 0.9,5.0,1.0,10.0,134.0,103.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,0.0,9
117,2000,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
118,2001,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
119,2002,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
120,2003,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
121,2004,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
122,2005,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
123,2006,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
124,2007,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
125,2008,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
126,2009,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
127,2010,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
128,2011,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10
129,2012,No Magnitude,3120.0,2807.0,2938.0,3608.0,2939.0,864.0,828.0,1807.0,1922.0,17.0,24.0,11.0,3.0,10

In [23]:
#lastly,do the case when to modify the table
pysqldf("""
SELECT a.year,
       a.magnitude,
       CASE WHEN a.year = 2000 THEN a.year_2000 
            WHEN a.year = 2001 THEN a.year_2001
            WHEN a.year = 2002 THEN a.year_2002
            WHEN a.year = 2003 THEN a.year_2003
            WHEN a.year = 2004 THEN a.year_2004
            WHEN a.year = 2005 THEN a.year_2005
            WHEN a.year = 2006 THEN a.year_2006
            WHEN a.year = 2007 THEN a.year_2007
            WHEN a.year = 2008 THEN a.year_2008
            WHEN a.year = 2009 THEN a.year_2009
            WHEN a.year = 2010 THEN a.year_2010
            WHEN a.year = 2011 THEN a.year_2011
            WHEN a.year = 2012 THEN a.year_2012
            ELSE NULL END AS number_of_earthq
FROM
(SELECT
    test.year as year,
    df.*
FROM df
CROSS JOIN
(SELECT years.*
        FROM 
    (   SELECT 2000 AS year
        UNION SELECT 2001 UNION SELECT 2002 UNION SELECT 2003
        UNION SELECT 2004 UNION SELECT 2005 UNION SELECT 2006
        UNION SELECT 2007 UNION SELECT 2008 UNION SELECT 2009
        UNION SELECT 2010 UNION SELECT 2011 UNION SELECT 2012
    ) years
 ) test
 ) a 
""")

     year     magnitude  number_of_earthq
0    2000    8.0 to 9.9               1.0
1    2001    8.0 to 9.9               1.0
2    2002    8.0 to 9.9               0.0
3    2003    8.0 to 9.9               1.0
4    2004    8.0 to 9.9               2.0
5    2005    8.0 to 9.9               1.0
6    2006    8.0 to 9.9               2.0
7    2007    8.0 to 9.9               4.0
8    2008    8.0 to 9.9               0.0
9    2009    8.0 to 9.9               1.0
10   2010    8.0 to 9.9               1.0
11   2011    8.0 to 9.9               1.0
12   2012    8.0 to 9.9               2.0
13   2000    7.0 to 7.9              14.0
14   2001    7.0 to 7.9              15.0
15   2002    7.0 to 7.9              13.0
16   2003    7.0 to 7.9              14.0
17   2004    7.0 to 7.9              14.0
18   2005    7.0 to 7.9              10.0
19   2006    7.0 to 7.9               9.0
20   2007    7.0 to 7.9              14.0
21   2008    7.0 to 7.9              12.0
22   2009    7.0 to 7.9              16.0
23   2010    7.0 to 7.9              23.0
24   2011    7.0 to 7.9              19.0
25   2012    7.0 to 7.9              12.0
26   2000    6.0 to 6.9             146.0
27   2001    6.0 to 6.9             121.0
28   2002    6.0 to 6.9             127.0
29   2003    6.0 to 6.9             140.0
..    ...           ...               ...
100  2009    1.0 to 1.9              26.0
101  2010    1.0 to 1.9              39.0
102  2011    1.0 to 1.9              47.0
103  2012    1.0 to 1.9              43.0
104  2000    0.1 to 0.9               5.0
105  2001    0.1 to 0.9               1.0
106  2002    0.1 to 0.9              10.0
107  2003    0.1 to 0.9             134.0
108  2004    0.1 to 0.9             103.0
109  2005    0.1 to 0.9               0.0
110  2006    0.1 to 0.9               2.0
111  2007    0.1 to 0.9               2.0
112  2008    0.1 to 0.9               0.0
113  2009    0.1 to 0.9               1.0
114  2010    0.1 to 0.9               0.0
115  2011    0.1 to 0.9               1.0
116  2012    0.1 to 0.9               0.0
117  2000  No Magnitude            3120.0
118  2001  No Magnitude            2807.0
119  2002  No Magnitude            2938.0
120  2003  No Magnitude            3608.0
121  2004  No Magnitude            2939.0
122  2005  No Magnitude             864.0
123  2006  No Magnitude             828.0
124  2007  No Magnitude            1807.0
125  2008  No Magnitude            1922.0
126  2009  No Magnitude              17.0
127  2010  No Magnitude              24.0
128  2011  No Magnitude              11.0
129  2012  No Magnitude               3.0

[130 rows x 3 columns]